In [1]:
import numpy as np

# Creating Arrays

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 6.9)

array([6.9, 6.9, 6.9, 6.9, 6.9, 6.9, 6.9, 6.9, 6.9, 6.9])

In [5]:
list1 = [1,2,3,4,5]
a = np.array(list1)

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
a[2] = 12345

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [12]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Multi - Dimensional arrays

In [13]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [21]:
# from list of list
n = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

In [22]:
n

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
n[0][4]

5

In [20]:
n[:,1]

array([2, 7])

# Randomly generated arays

In [25]:
np.random.seed(2) # to get the same matrix
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [32]:
np.random.seed(2) # to get the same matrix
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [33]:
np.random.seed(2) # to get the same matrix
np.random.randn(5,2) * 100

array([[ -41.67578474,   -5.62668272],
       [-213.61960957,  164.02708084],
       [-179.34355852,  -84.17473657],
       [  50.28814172, -124.52880866],
       [-105.79522189,  -90.90076149]])

In [31]:
np.random.seed(2) # to get the same matrix
np.random.randint(low=0, high=100.,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [34]:
a = np.arange(5)

In [35]:
b = (10 + (a*2))** 2/100

In [36]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

# Comparison Operation

In [39]:
a >= 2 

array([False, False,  True,  True,  True])

In [40]:
a > b

array([False, False,  True,  True,  True])

In [41]:
a[a > b]

array([2, 3, 4])

# Summarizing Operation

In [42]:
a

array([0, 1, 2, 3, 4])

In [43]:
a.sum()

10

In [44]:
a.std()

1.4142135623730951

# Vector Vector Multiplication --> Dot Product

In [45]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result



In [50]:
vector_vector_multiplication(np.array([1,2,3]), np.array([4,5,6]))

32.0

# Matrix vector multiplication

In [51]:
vec1 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [2,3,4,5]
])

vec2 = np.array([1,1,1,1])

In [52]:
vec1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5]])

In [55]:
vec1.shape

(3, 4)

In [53]:
vec2

array([1, 1, 1, 1])

In [57]:
def matrix_vector_multiplication1(vec1, vec2):
    assert vec1.shape[1] == vec2.shape[0]

    runs = vec1.shape[0]
    val_counts = vec1.shape[1]
    res_vec = []
    for i in range(runs):
        result = 0
        for j in range(val_counts):
            result = result + vec1[i][j] * vec2[j]
        res_vec.append(result)
    return np.array(res_vec)



In [61]:
def matrix_vector_multiplication2(vec1, vec2):
    assert vec1.shape[1] == vec2.shape[0]
    num_rows = vec1.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(vec1[i], vec2)

    return result


In [58]:
matrix_vector_multiplication1(vec1, vec2)

array([10, 26, 14])

In [62]:
matrix_vector_multiplication2(vec1, vec2)

array([10., 26., 14.])

In [63]:
vec1.dot(vec2)

array([10, 26, 14])